### ISSUE TITLE
Düzeltilmeli

### ISSUE THREAD

**Issue by nskrkmz** [akiffeyzioglu/docker-notes#2]
Aşağıda belirtilenler için [buraya tıklayın](https://github.com/akiffeyzioglu/docker-notes#Docker-Komutlar%C4%B1)

* `docker run hello-world` "hello-world adında container çalıştırır." ifadesi düzenlenmeli hello-world isimli image dan bir container çalıştırır (--name eklenmediği için container ismi docker daemon tarafından rastgele tanımlanır )
* `docker run --rm -it hello-world sh` " "--rm" container oluşturulduktan sonra sil demektir. " ifadesi container kapandıktan sonra sil anlamına gelir. interaktif bağlanılan containerdanexit yapılmadan çıkılmak istenirse Ctrl+PQ kullanılabilir 'docker container stop id_foo' çalıştırıldığında ilgili container silinir.

**Comment by akiffeyzioglu** [comment]
Uyarınız için teşekkür ederim. Düzeltildi.
