### ISSUE TITLE
Dockerfile | Duzeltme onerisi

### ISSUE THREAD

**Issue by nskrkmz** [akiffeyzioglu/docker-notes#4]
Öncelikle selamlar. Dockerfile basligi altinda ufak bir duzeltme tavsiyem var.
Orjinal ifade :
```
* Dockerfile dosyası oluşturulurken "Dockerfile" şeklinde oluşturulmalıdır. Uzantı belirtilmesine gerek yoktur.
```
Cümleden dosyamızı Dockerfile olarak isimlendirmemizin bir zorunluluk olduğu anlaşılıyor ancak "Dockerfile" default olan dosya ismidir. Ozel bir Dockerfile olusturulup derlenebilir. [Ufak bir ornek](https://www.kindacode.com/article/docker-build-with-custom-dockerfile-name/)

**Comment by akiffeyzioglu** [comment]
Selam,

Öneriniz için teşekkür ederim. Düzeltmeyi yaptım.
